### ISSUE TITLE
All arrays must have the same number of element when using the dot product scatter method

### ISSUE THREAD

**Issue by josruirod** [vetscience/Assemblosis#3]
Hi,

Thanks for the work and for sharing Assemblosis. I've been trying to apply your pipeline to our own data and I'm encountering a problemin the work flow.
The error is "All arrays must have the same number of element when using the dot product scatter method". I'm not familia with CWL, so I'm not sure which could be the problem.

Do you have any idea or suggestion or could provide any support?  I attach below the end of the terminal output where there is the first error, in case is of help. I also attach the yml I used (had to tweak it a bit, adding $namesspaces and pacBioTmpDir)

Thanks for your time

Error:
`[2020-07-20 08:26:46,10] [info] WorkflowExecutionActor-189188b3-e8ab-461c-b897-31572652cb2b [[38;5;2m189188b3[0m]: Starting hdf5check
[2020-07-20 08:26:46,30] [[38;5;1merror[0m] Workflow execution failure:
All arrays must have the same number of element when using the dot product scatter method
common.exception.AggregatedMessageException: Workflow execution failure:
All arrays must have the same number of element when using the dot product scatter method
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$9(WorkflowExecutionActor.scala:534)
	at cats.data.Validated.valueOr(Validated.scala:48)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableNodes(WorkflowExecutionActor.scala:533)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:188)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:186)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:168)
	at akka.actor.FSM.processEvent(FSM.scala:687)
	at akka.actor.FSM.processEvent$(FSM.scala:681)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$LoggingFSM$$super$processEvent(WorkflowExecutionActor.scala:51)
	at akka.actor.LoggingFSM.processEvent(FSM.scala:820)
	at akka.actor.LoggingFSM.processEvent$(FSM.scala:802)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.processEvent(WorkflowExecutionActor.scala:51)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:678)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:672)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.akka$actor$Timers$$super$aroundReceive(WorkflowExecutionActor.scala:51)
	at akka.actor.Timers.aroundReceive(Timers.scala:51)
	at akka.actor.Timers.aroundReceive$(Timers.scala:40)
	at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.aroundReceive(WorkflowExecutionActor.scala:51)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
`

yaml file:
[assemblyPfal.yml.txt](https://github.com/vetscience/Assemblosis/files/4946474/assemblyPfal.yml.txt)

**Comment by pckorhon** [comment]
Hi, I think that in your .yml phredsPe should be:
phredsPe: ['33']
because you have only one pair of fastq files.

**Comment by josruirod** [comment]
Oh thanks!, I totally overlooked that. What about:
maxFragmentLens: [800,800]
Should that also be only one?
maxFragmentLens: [800]

Thank you very much for the support

**Comment by pckorhon** [comment]
Sure, that would give the same error.
